export interface ModelInfo {
  service: ModelServices;
  provider: string;
  modelName: string;
  version: string;
  modelId: ModelIds;
  modelArn: string;
  pricePerThousandInputTokens: number;
  pricePerThousandOutputTokens: number;
  isStreamingSupported: boolean;
}

export enum ModelServices {
  AWSBedrock = 'AWS Bedrock',
}

export enum ModelIds {
  AI21_J2_MID_V1 = 'ai21.j2-mid-v1',
  AI21_J2_ULTRA_V1 = 'ai21.j2-ultra-v1',
  AMAZON_TITAN_TEXT_LITE_V1 = 'amazon.titan-text-lite-v1',
  AMAZON_TITAN_TEXT_EXPRESS_V1 = 'amazon.titan-text-express-v1',
  // ANTHROPIC_CLAUDE_V1 = 'anthropic.claude-v1',
  // ANTHROPIC_CLAUDE_V2 = 'anthropic.claude-v2',
  // ANTHROPIC_CLAUDE_V2_1 = 'anthropic.claude-v2:1',
  ANTHROPIC_CLAUDE_3_SONNET_20240229_V1_0 = 'anthropic.claude-3-sonnet-20240229-v1:0',
  // ANTHROPIC_CLAUDE_3_5_SONNET_20240620_V1_0 = 'anthropic.claude-3-5-sonnet-20240620-v1:0',
  ANTHROPIC_CLAUDE_3_HAIKU_20240307_V1_0 = 'anthropic.claude-3-haiku-20240307-v1:0',
  // ANTHROPIC_CLAUDE_INSTANT_V1 = 'anthropic.claude-instant-v1',
  COHERE_COMMAND_TEXT_V14 = 'cohere.command-text-v14',
  COHERE_COMMAND_LIGHT_TEXT_V14 = 'cohere.command-light-text-v14',
  META_LLAMA2_13B_CHAT_V1 = 'meta.llama2-13b-chat-v1',
  META_LLAMA2_70B_CHAT_V1 = 'meta.llama2-70b-chat-v1',
  MISTRAL_MISTRAL_7B_INSTRUCT_V0_2 = 'mistral.mistral-7b-instruct-v0:2',
  MISTRAL_MIXTRAL_8X7B_INSTRUCT_V0_1 = 'mistral.mixtral-8x7b-instruct-v0:1',
}

export const MODELS: ModelInfo[] = [
  {
    service: ModelServices.AWSBedrock,
    provider: 'AI21 Labs',
    modelName: 'Jurassic-2 Mid',
    version: '1.x',
    modelId: ModelIds.AI21_J2_MID_V1,
    modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/ai21.j2-mid-v1',
    pricePerThousandInputTokens: 0.0125,
    pricePerThousandOutputTokens: 0.0125,
    isStreamingSupported: false,
  },
  {
    service: ModelServices.AWSBedrock,
    provider: 'AI21 Labs',
    modelName: 'Jurassic-2 Ultra',
    version: '1.x',
    modelId: ModelIds.AI21_J2_ULTRA_V1,
    modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/ai21.j2-ultra-v1',
    pricePerThousandInputTokens: 0.0188,
    pricePerThousandOutputTokens: 0.0188,
    isStreamingSupported: false,
  },
  {
    service: ModelServices.AWSBedrock,
    provider: 'Amazon',
    modelName: 'Titan Text G1 - Lite',
    version: '1.x',
    modelId: ModelIds.AMAZON_TITAN_TEXT_LITE_V1,
    modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-text-lite-v1',
    pricePerThousandInputTokens: 0.0003,
    pricePerThousandOutputTokens: 0.0004,
    isStreamingSupported: true,
  },
  {
    service: ModelServices.AWSBedrock,
    provider: 'Amazon',
    modelName: 'Titan Text G1 - Express',
    version: '1.x',
    modelId: ModelIds.AMAZON_TITAN_TEXT_EXPRESS_V1,
    modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-text-express-v1',
    pricePerThousandInputTokens: 0.0008,
    pricePerThousandOutputTokens: 0.0016,
    isStreamingSupported: true,
  },
  // {
  //   service: ModelServices.AWSBedrock,
  //   provider: 'Anthropic',
  //   modelName: 'Claude 2.1',
  //   version: '2.x',
  //   modelId: ModelIds.ANTHROPIC_CLAUDE_V2_1,
  //   modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-v2:1',
  //   pricePerThousandInputTokens: 0.008,
  //   pricePerThousandOutputTokens: 0.024,
  //   isStreamingSupported: true,
  // },
  // {
  //   service: ModelServices.AWSBedrock,
  //   provider: 'Anthropic',
  //   modelName: 'Claude 2',
  //   version: '2.x',
  //   modelId: ModelIds.ANTHROPIC_CLAUDE_V2,
  //   modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-v2',
  //   pricePerThousandInputTokens: 0.008,
  //   pricePerThousandOutputTokens: 0.024,
  //   isStreamingSupported: true,
  // },
  {
    service: ModelServices.AWSBedrock,
    provider: 'Anthropic',
    modelName: 'Claude 3 Sonnet',
    version: '3.x',
    modelId: ModelIds.ANTHROPIC_CLAUDE_3_SONNET_20240229_V1_0,
    modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0',
    pricePerThousandInputTokens: 0.003,
    pricePerThousandOutputTokens: 0.015,
    isStreamingSupported: true,
  },
  // {
  //   service: ModelServices.AWSBedrock,
  //   provider: 'Anthropic',
  //   modelName: 'Claude 3.5 Sonnet',
  //   version: 'v1',
  //   modelId: ModelIds.ANTHROPIC_CLAUDE_3_5_SONNET_20240620_V1_0,
  //   modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0',
  //   pricePerThousandInputTokens: 0.003,
  //   pricePerThousandOutputTokens: 0.015,
  //   isStreamingSupported: true,
  // },
  {
    service: ModelServices.AWSBedrock,
    provider: 'Anthropic',
    modelName: 'Claude 3 Haiku',
    version: '3.x',
    modelId: ModelIds.ANTHROPIC_CLAUDE_3_HAIKU_20240307_V1_0,
    modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-haiku-20240307-v1:0',
    pricePerThousandInputTokens: 0.00025,
    pricePerThousandOutputTokens: 0.00125,
    isStreamingSupported: true,
  },
  // {
  //   service: ModelServices.AWSBedrock,
  //   provider: 'Anthropic',
  //   modelName: 'Claude Instant',
  //   version: '1.x',
  //   modelId: ModelIds.ANTHROPIC_CLAUDE_INSTANT_V1,
  //   modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-instant-v1',
  //   pricePerThousandInputTokens: 0.00163,
  //   pricePerThousandOutputTokens: 0.00551,
  //   isStreamingSupported: true,
  // },
  {
    service: ModelServices.AWSBedrock,
    provider: 'Cohere',
    modelName: 'Command',
    version: '14.x',
    modelId: ModelIds.COHERE_COMMAND_TEXT_V14,
    modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/cohere.command-text-v14',
    pricePerThousandInputTokens: 0.0015,
    pricePerThousandOutputTokens: 0.002,
    isStreamingSupported: false,
  },
  {
    service: ModelServices.AWSBedrock,
    provider: 'Cohere',
    modelName: 'Command Light',
    version: '15.x',
    modelId: ModelIds.COHERE_COMMAND_LIGHT_TEXT_V14,
    modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/cohere.command-light-text-v14',
    pricePerThousandInputTokens: 0.0003,
    pricePerThousandOutputTokens: 0.0006,
    isStreamingSupported: false,
  },

  {
    service: ModelServices.AWSBedrock,
    provider: 'Meta',
    modelName: 'Llama 2 Chat 13B',
    version: '1.x',
    modelId: ModelIds.META_LLAMA2_13B_CHAT_V1,
    modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/meta.llama2-13b-chat-v1',
    pricePerThousandInputTokens: 0.00075,
    pricePerThousandOutputTokens: 0.001,
    isStreamingSupported: true,
  },
  {
    service: ModelServices.AWSBedrock,
    provider: 'Meta',
    modelName: 'Llama 2 Chat 70B',
    version: '1.x',
    modelId: ModelIds.META_LLAMA2_70B_CHAT_V1,
    modelArn: 'arn:aws:bedrock:us-east-1::foundation-model/meta.llama2-70b-chat-v1',
    pricePerThousandInputTokens: 0.00195,
    pricePerThousandOutputTokens: 0.00256,
    isStreamingSupported: true,
  },
  {
    service: ModelServices.AWSBedrock,
    provider: 'Mistral AI',
    modelName: 'Mistral 7B Instruct',
    version: '0.x',
    modelId: ModelIds.MISTRAL_MISTRAL_7B_INSTRUCT_V0_2,
    modelArn: 'arn:aws:bedrock:us-west-2::foundation-model/mistral.mistral-7b-instruct-v0:2',
    pricePerThousandInputTokens: 0.00015,
    pricePerThousandOutputTokens: 0.0002,
    isStreamingSupported: true,
  },
  {
    service: ModelServices.AWSBedrock,
    provider: 'Mistral AI',
    modelName: 'Mixtral 8x7B Instruct',
    version: '0.x',
    modelId: ModelIds.MISTRAL_MIXTRAL_8X7B_INSTRUCT_V0_1,
    modelArn: 'arn:aws:bedrock:us-west-2::foundation-model/mistral.mixtral-8x7b-instruct-v0:1',
    pricePerThousandInputTokens: 0.00045,
    pricePerThousandOutputTokens: 0.0007,
    isStreamingSupported: true,
  },
];

export const getModelInfoByModelId = (modelId: string): ModelInfo | undefined =>
  MODELS.find((model) => model.modelId === modelId);
